# Generated by Django 3.2 on 2022-02-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, null=True, unique=True, verbose_name='候选人ID')),
                ('username', models.CharField(max_length=135, verbose_name='姓名')),
                ('user_age', models.IntegerField(verbose_name='年龄')),
                ('user_city', models.CharField(max_length=135, verbose_name='城市')),
                ('user_phone', models.CharField(max_length=135, verbose_name='手机号码')),
                ('user_email', models.CharField(blank=True, max_length=135, verbose_name='邮箱')),
                ('user_address', models.CharField(blank=True, max_length=135, verbose_name='籍贯')),
                ('user_gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=135, verbose_name='性别')),
                ('user_remark', models.CharField(blank=True, max_length=135, verbose_name='备注')),
                ('user_major', models.CharField(blank=True, max_length=135, verbose_name='专业')),
                ('user_degree', models.CharField(blank=True, choices=[('本科', '本科'), ('硕士', '硕士'), ('博士', '博士')], max_length=135, verbose_name='学历')),
                ('user_identity', models.CharField(choices=[('群众', '群众'), ('团员', '团员'), ('成年团员', '成年团员'), ('积极分子', '积极分子'), ('预备党员', '预备党员'), ('党员', '党员')], max_length=135, verbose_name='政治面貌')),
                ('branch_manager', models.CharField(blank=True, max_length=256, verbose_name='支部管理员')),
                ('branch_comment', models.TextField(blank=True, max_length=1024, verbose_name='支部意见')),
                ('master_manager', models.CharField(blank=True, max_length=135, verbose_name='总管理员')),
                ('audit_result', models.CharField(choices=[('通过', '通过'), ('待审核', '待审核'), ('否决', '否决')], max_length=135, verbose_name='审核结果')),
                ('audit_comment', models.TextField(blank=True, max_length=1024, verbose_name='审核意见')),
                ('audit_date', models.DateTimeField(auto_now=True, verbose_name='审核时间')),
                ('audit_modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='审核更新时间')),
                ('audit_last_editor', models.CharField(blank=True, max_length=256, verbose_name='最后审核者')),
                ('creator', models.CharField(blank=True, max_length=256, verbose_name='候选人数据创建者')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('last_editor', models.CharField(blank=True, max_length=256, verbose_name='最后编辑者')),
            ],
            options={
                'verbose_name': '候选人',
                'verbose_name_plural': '候选人',
                'db_table': 'candidate',
            },
        ),
    ]
