# Generated by Django 3.2 on 2022-02-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jionparty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='branch_name',
            field=models.CharField(blank=True, max_length=256, verbose_name='支部名称'),
        ),
    ]
