# Generated by Django 3.2 on 2022-02-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jionparty', '0002_candidate_branch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='user_college',
            field=models.CharField(blank=True, max_length=135, verbose_name='学院'),
        ),
    ]
