# Generated by Django 3.2 on 2022-02-28 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jionparty', '0003_candidate_user_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='branch_manager',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='master_manager',
        ),
        migrations.AddField(
            model_name='candidate',
            name='branch_manager_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_manager_user', to=settings.AUTH_USER_MODEL, verbose_name='支部管理员'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='master_manager_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maser_manager_user', to=settings.AUTH_USER_MODEL, verbose_name='总管理员'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='branch_comment',
            field=models.TextField(blank=True, help_text='该位同志各方面表现情况', max_length=1024, verbose_name='支部意见'),
        ),
    ]
