# Generated by Django 3.2 on 2022-03-01 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jionparty', '0005_alter_candidate_master_manager_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'permissions': [('export', '能导出候选人数据')], 'verbose_name': '候选人', 'verbose_name_plural': '候选人'},
        ),
    ]
