# Generated by Django 3.2 on 2022-03-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jionparty', '0007_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='college',
            field=models.CharField(blank=True, max_length=135, verbose_name='学院'),
        ),
    ]
