# Generated by Django 3.2 on 2022-03-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jionparty', '0008_alter_application_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='user_age',
            field=models.IntegerField(blank=True, verbose_name='年龄'),
        ),
    ]
