# Generated by Django 3.2 on 2022-03-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jionparty', '0009_alter_candidate_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='user_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
    ]
