# Generated by Django 3.2 on 2022-03-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jionparty', '0010_auto_20220304_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='user_grade',
            field=models.CharField(blank=True, max_length=135, verbose_name='年级'),
        ),
    ]
