# Generated by Django 3.2 on 2022-03-04 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jionparty', '0011_candidate_user_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'permissions': [('export', '能导出候选人数据'), ('process', '提交审批')], 'verbose_name': '候选人', 'verbose_name_plural': '候选人'},
        ),
    ]
