# Generated by Django 3.2 on 2022-03-04 14:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='studyFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.SmallIntegerField(choices=[(0, '活动'), (1, '会议'), (2, '通告'), (3, '新闻'), (4, '学习')], verbose_name='文件类型')),
                ('file_name', models.CharField(max_length=250, verbose_name='文件名称')),
                ('file_content', models.FileField(upload_to='file/', verbose_name='学习文件')),
                ('create_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建日期')),
                ('modified_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='修改日期')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '学习文件',
                'verbose_name_plural': '学习文件',
                'db_table': 'studyFile',
            },
        ),
    ]
