# Generated by Django 3.2 on 2022-03-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyfiles',
            name='file_http',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='在线地址'),
        ),
    ]
