# Generated by Django 3.2 on 2022-03-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyfiles', '0002_studyfiles_file_http'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyfiles',
            name='file_type',
            field=models.SmallIntegerField(choices=[(0, '活动'), (1, '会议'), (2, '通告'), (3, '学习')], null=True, verbose_name='文件类型'),
        ),
    ]
