# Generated by Django 3.2 on 2022-02-28 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_type', models.SmallIntegerField(choices=[(0, '活动'), (1, '会议'), (2, '通告'), (3, '新闻')], verbose_name='通知类别')),
                ('notice_name', models.CharField(max_length=250, verbose_name='通知名称')),
                ('notice_content', models.TextField(max_length=1024, verbose_name='通知内容')),
                ('create_date', models.DateTimeField(verbose_name='创建日期')),
                ('modified_date', models.DateTimeField(verbose_name='修改日期')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'notice',
            },
        ),
    ]
