# Generated by Django 3.2 on 2022-02-28 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='修改日期'),
        ),
    ]
